//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfigApp.PaymentEngine {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardBalanceRequest", Namespace="http://schema.bloyal.com/3.5")]
    [System.SerializableAttribute()]
    public partial class CardBalanceRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardPinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CustomerUidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SwipedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenderCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardPin {
            get {
                return this.CardPinField;
            }
            set {
                if ((object.ReferenceEquals(this.CardPinField, value) != true)) {
                    this.CardPinField = value;
                    this.RaisePropertyChanged("CardPin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CustomerUid {
            get {
                return this.CustomerUidField;
            }
            set {
                if ((this.CustomerUidField.Equals(value) != true)) {
                    this.CustomerUidField = value;
                    this.RaisePropertyChanged("CustomerUid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Swiped {
            get {
                return this.SwipedField;
            }
            set {
                if ((this.SwipedField.Equals(value) != true)) {
                    this.SwipedField = value;
                    this.RaisePropertyChanged("Swiped");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenderCode {
            get {
                return this.TenderCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TenderCodeField, value) != true)) {
                    this.TenderCodeField = value;
                    this.RaisePropertyChanged("TenderCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionExternalId {
            get {
                return this.TransactionExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionExternalIdField, value) != true)) {
                    this.TransactionExternalIdField = value;
                    this.RaisePropertyChanged("TransactionExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionToken {
            get {
                return this.TransactionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTokenField, value) != true)) {
                    this.TransactionTokenField = value;
                    this.RaisePropertyChanged("TransactionToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardResponse", Namespace="http://schema.bloyal.com/3.5")]
    [System.SerializableAttribute()]
    public partial class CardResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorizationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AvailableBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CurrentBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConfigApp.PaymentEngine.CardRequestStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorizationCode {
            get {
                return this.AuthorizationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorizationCodeField, value) != true)) {
                    this.AuthorizationCodeField = value;
                    this.RaisePropertyChanged("AuthorizationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AvailableBalance {
            get {
                return this.AvailableBalanceField;
            }
            set {
                if ((this.AvailableBalanceField.Equals(value) != true)) {
                    this.AvailableBalanceField = value;
                    this.RaisePropertyChanged("AvailableBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurrentBalance {
            get {
                return this.CurrentBalanceField;
            }
            set {
                if ((this.CurrentBalanceField.Equals(value) != true)) {
                    this.CurrentBalanceField = value;
                    this.RaisePropertyChanged("CurrentBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConfigApp.PaymentEngine.CardRequestStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionCode {
            get {
                return this.TransactionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionCodeField, value) != true)) {
                    this.TransactionCodeField = value;
                    this.RaisePropertyChanged("TransactionCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardRequestStatus", Namespace="http://schema.bloyal.com/3.5")]
    public enum CardRequestStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approved = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Declined = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Invalid = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bypass = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseFault", Namespace="http://schema.bloyal.com/3.5")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConfigApp.PaymentEngine.RedirectFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConfigApp.PaymentEngine.SystemFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConfigApp.PaymentEngine.BusinessFault))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ConfigApp.PaymentEngine.SecurityFault))]
    public partial class BaseFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.ServiceModel.ExceptionDetail ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.ServiceModel.ExceptionDetail Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RedirectFault", Namespace="http://schema.bloyal.com/3.5")]
    [System.SerializableAttribute()]
    public partial class RedirectFault : ConfigApp.PaymentEngine.BaseFault {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RedirectBaseUriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RedirectBaseUri {
            get {
                return this.RedirectBaseUriField;
            }
            set {
                if ((object.ReferenceEquals(this.RedirectBaseUriField, value) != true)) {
                    this.RedirectBaseUriField = value;
                    this.RaisePropertyChanged("RedirectBaseUri");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemFault", Namespace="http://schema.bloyal.com/3.5")]
    [System.SerializableAttribute()]
    public partial class SystemFault : ConfigApp.PaymentEngine.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessFault", Namespace="http://schema.bloyal.com/3.5")]
    [System.SerializableAttribute()]
    public partial class BusinessFault : ConfigApp.PaymentEngine.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFault", Namespace="http://schema.bloyal.com/3.5")]
    [System.SerializableAttribute()]
    public partial class SecurityFault : ConfigApp.PaymentEngine.BaseFault {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardCreditRequest", Namespace="http://schema.bloyal.com/3.5")]
    [System.SerializableAttribute()]
    public partial class CardCreditRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowDuplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CustomerUidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SwipedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenderCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowDuplicate {
            get {
                return this.AllowDuplicateField;
            }
            set {
                if ((this.AllowDuplicateField.Equals(value) != true)) {
                    this.AllowDuplicateField = value;
                    this.RaisePropertyChanged("AllowDuplicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CustomerUid {
            get {
                return this.CustomerUidField;
            }
            set {
                if ((this.CustomerUidField.Equals(value) != true)) {
                    this.CustomerUidField = value;
                    this.RaisePropertyChanged("CustomerUid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Swiped {
            get {
                return this.SwipedField;
            }
            set {
                if ((this.SwipedField.Equals(value) != true)) {
                    this.SwipedField = value;
                    this.RaisePropertyChanged("Swiped");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenderCode {
            get {
                return this.TenderCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TenderCodeField, value) != true)) {
                    this.TenderCodeField = value;
                    this.RaisePropertyChanged("TenderCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionExternalId {
            get {
                return this.TransactionExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionExternalIdField, value) != true)) {
                    this.TransactionExternalIdField = value;
                    this.RaisePropertyChanged("TransactionExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionToken {
            get {
                return this.TransactionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTokenField, value) != true)) {
                    this.TransactionTokenField = value;
                    this.RaisePropertyChanged("TransactionToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardRedeemRequest", Namespace="http://schema.bloyal.com/3.5")]
    [System.SerializableAttribute()]
    public partial class CardRedeemRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowDuplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardPinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CustomerUidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SwipedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenderCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowDuplicate {
            get {
                return this.AllowDuplicateField;
            }
            set {
                if ((this.AllowDuplicateField.Equals(value) != true)) {
                    this.AllowDuplicateField = value;
                    this.RaisePropertyChanged("AllowDuplicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardPin {
            get {
                return this.CardPinField;
            }
            set {
                if ((object.ReferenceEquals(this.CardPinField, value) != true)) {
                    this.CardPinField = value;
                    this.RaisePropertyChanged("CardPin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CustomerUid {
            get {
                return this.CustomerUidField;
            }
            set {
                if ((this.CustomerUidField.Equals(value) != true)) {
                    this.CustomerUidField = value;
                    this.RaisePropertyChanged("CustomerUid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Swiped {
            get {
                return this.SwipedField;
            }
            set {
                if ((this.SwipedField.Equals(value) != true)) {
                    this.SwipedField = value;
                    this.RaisePropertyChanged("Swiped");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenderCode {
            get {
                return this.TenderCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TenderCodeField, value) != true)) {
                    this.TenderCodeField = value;
                    this.RaisePropertyChanged("TenderCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionExternalId {
            get {
                return this.TransactionExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionExternalIdField, value) != true)) {
                    this.TransactionExternalIdField = value;
                    this.RaisePropertyChanged("TransactionExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionToken {
            get {
                return this.TransactionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTokenField, value) != true)) {
                    this.TransactionTokenField = value;
                    this.RaisePropertyChanged("TransactionToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardDebitRequest", Namespace="http://schema.bloyal.com/3.5")]
    [System.SerializableAttribute()]
    public partial class CardDebitRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowDuplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowDuplicate {
            get {
                return this.AllowDuplicateField;
            }
            set {
                if ((this.AllowDuplicateField.Equals(value) != true)) {
                    this.AllowDuplicateField = value;
                    this.RaisePropertyChanged("AllowDuplicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionCode {
            get {
                return this.TransactionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionCodeField, value) != true)) {
                    this.TransactionCodeField = value;
                    this.RaisePropertyChanged("TransactionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionExternalId {
            get {
                return this.TransactionExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionExternalIdField, value) != true)) {
                    this.TransactionExternalIdField = value;
                    this.RaisePropertyChanged("TransactionExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionToken {
            get {
                return this.TransactionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTokenField, value) != true)) {
                    this.TransactionTokenField = value;
                    this.RaisePropertyChanged("TransactionToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardRefundRequest", Namespace="http://schema.bloyal.com/3.5")]
    [System.SerializableAttribute()]
    public partial class CardRefundRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowDuplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowDuplicate {
            get {
                return this.AllowDuplicateField;
            }
            set {
                if ((this.AllowDuplicateField.Equals(value) != true)) {
                    this.AllowDuplicateField = value;
                    this.RaisePropertyChanged("AllowDuplicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionCode {
            get {
                return this.TransactionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionCodeField, value) != true)) {
                    this.TransactionCodeField = value;
                    this.RaisePropertyChanged("TransactionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionExternalId {
            get {
                return this.TransactionExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionExternalIdField, value) != true)) {
                    this.TransactionExternalIdField = value;
                    this.RaisePropertyChanged("TransactionExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionToken {
            get {
                return this.TransactionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTokenField, value) != true)) {
                    this.TransactionTokenField = value;
                    this.RaisePropertyChanged("TransactionToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardAuthorizeRequest", Namespace="http://schema.bloyal.com/3.5")]
    [System.SerializableAttribute()]
    public partial class CardAuthorizeRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowDuplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardPinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CustomerUidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SwipedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenderCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowDuplicate {
            get {
                return this.AllowDuplicateField;
            }
            set {
                if ((this.AllowDuplicateField.Equals(value) != true)) {
                    this.AllowDuplicateField = value;
                    this.RaisePropertyChanged("AllowDuplicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardNumber {
            get {
                return this.CardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CardNumberField, value) != true)) {
                    this.CardNumberField = value;
                    this.RaisePropertyChanged("CardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardPin {
            get {
                return this.CardPinField;
            }
            set {
                if ((object.ReferenceEquals(this.CardPinField, value) != true)) {
                    this.CardPinField = value;
                    this.RaisePropertyChanged("CardPin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CustomerUid {
            get {
                return this.CustomerUidField;
            }
            set {
                if ((this.CustomerUidField.Equals(value) != true)) {
                    this.CustomerUidField = value;
                    this.RaisePropertyChanged("CustomerUid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Swiped {
            get {
                return this.SwipedField;
            }
            set {
                if ((this.SwipedField.Equals(value) != true)) {
                    this.SwipedField = value;
                    this.RaisePropertyChanged("Swiped");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenderCode {
            get {
                return this.TenderCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TenderCodeField, value) != true)) {
                    this.TenderCodeField = value;
                    this.RaisePropertyChanged("TenderCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionExternalId {
            get {
                return this.TransactionExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionExternalIdField, value) != true)) {
                    this.TransactionExternalIdField = value;
                    this.RaisePropertyChanged("TransactionExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionToken {
            get {
                return this.TransactionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTokenField, value) != true)) {
                    this.TransactionTokenField = value;
                    this.RaisePropertyChanged("TransactionToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardReleaseRequest", Namespace="http://schema.bloyal.com/3.5")]
    [System.SerializableAttribute()]
    public partial class CardReleaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceField, value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionCode {
            get {
                return this.TransactionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionCodeField, value) != true)) {
                    this.TransactionCodeField = value;
                    this.RaisePropertyChanged("TransactionCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardCaptureRequest", Namespace="http://schema.bloyal.com/3.5")]
    [System.SerializableAttribute()]
    public partial class CardCaptureRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowDuplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionExternalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowDuplicate {
            get {
                return this.AllowDuplicateField;
            }
            set {
                if ((this.AllowDuplicateField.Equals(value) != true)) {
                    this.AllowDuplicateField = value;
                    this.RaisePropertyChanged("AllowDuplicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionCode {
            get {
                return this.TransactionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionCodeField, value) != true)) {
                    this.TransactionCodeField = value;
                    this.RaisePropertyChanged("TransactionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionExternalId {
            get {
                return this.TransactionExternalIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionExternalIdField, value) != true)) {
                    this.TransactionExternalIdField = value;
                    this.RaisePropertyChanged("TransactionExternalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionToken {
            get {
                return this.TransactionTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTokenField, value) != true)) {
                    this.TransactionTokenField = value;
                    this.RaisePropertyChanged("TransactionToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.bloyal.com/3.5", ConfigurationName="PaymentEngine.PaymentEngine")]
    public interface PaymentEngine {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/GetCardBalance", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/GetCardBalanceResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SecurityFault), Action="http://service.bloyal.com/3.5/PaymentEngine/GetCardBalanceSecurityFaultFault", Name="SecurityFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.RedirectFault), Action="http://service.bloyal.com/3.5/PaymentEngine/GetCardBalanceRedirectFaultFault", Name="RedirectFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SystemFault), Action="http://service.bloyal.com/3.5/PaymentEngine/GetCardBalanceSystemFaultFault", Name="SystemFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.BusinessFault), Action="http://service.bloyal.com/3.5/PaymentEngine/GetCardBalanceBusinessFaultFault", Name="BusinessFault", Namespace="http://schema.bloyal.com/3.5")]
        ConfigApp.PaymentEngine.CardResponse GetCardBalance(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/GetCardBalance", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/GetCardBalanceResponse")]
        System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> GetCardBalanceAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/CardCredit", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/CardCreditResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SecurityFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardCreditSecurityFaultFault", Name="SecurityFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.RedirectFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardCreditRedirectFaultFault", Name="RedirectFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SystemFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardCreditSystemFaultFault", Name="SystemFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.BusinessFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardCreditBusinessFaultFault", Name="BusinessFault", Namespace="http://schema.bloyal.com/3.5")]
        ConfigApp.PaymentEngine.CardResponse CardCredit(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/CardCredit", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/CardCreditResponse")]
        System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> CardCreditAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/CardRedeem", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/CardRedeemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SecurityFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardRedeemSecurityFaultFault", Name="SecurityFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.RedirectFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardRedeemRedirectFaultFault", Name="RedirectFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SystemFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardRedeemSystemFaultFault", Name="SystemFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.BusinessFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardRedeemBusinessFaultFault", Name="BusinessFault", Namespace="http://schema.bloyal.com/3.5")]
        ConfigApp.PaymentEngine.CardResponse CardRedeem(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardRedeemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/CardRedeem", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/CardRedeemResponse")]
        System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> CardRedeemAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardRedeemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/CardDebit", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/CardDebitResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SecurityFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardDebitSecurityFaultFault", Name="SecurityFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.RedirectFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardDebitRedirectFaultFault", Name="RedirectFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SystemFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardDebitSystemFaultFault", Name="SystemFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.BusinessFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardDebitBusinessFaultFault", Name="BusinessFault", Namespace="http://schema.bloyal.com/3.5")]
        ConfigApp.PaymentEngine.CardResponse CardDebit(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardDebitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/CardDebit", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/CardDebitResponse")]
        System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> CardDebitAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardDebitRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/CardRefund", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/CardRefundResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SecurityFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardRefundSecurityFaultFault", Name="SecurityFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.RedirectFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardRefundRedirectFaultFault", Name="RedirectFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SystemFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardRefundSystemFaultFault", Name="SystemFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.BusinessFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardRefundBusinessFaultFault", Name="BusinessFault", Namespace="http://schema.bloyal.com/3.5")]
        ConfigApp.PaymentEngine.CardResponse CardRefund(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardRefundRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/CardRefund", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/CardRefundResponse")]
        System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> CardRefundAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardRefundRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/CardAuthorize", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/CardAuthorizeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SecurityFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardAuthorizeSecurityFaultFault", Name="SecurityFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.RedirectFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardAuthorizeRedirectFaultFault", Name="RedirectFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SystemFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardAuthorizeSystemFaultFault", Name="SystemFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.BusinessFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardAuthorizeBusinessFaultFault", Name="BusinessFault", Namespace="http://schema.bloyal.com/3.5")]
        ConfigApp.PaymentEngine.CardResponse CardAuthorize(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardAuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/CardAuthorize", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/CardAuthorizeResponse")]
        System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> CardAuthorizeAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardAuthorizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/CardRelease", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/CardReleaseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SecurityFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardReleaseSecurityFaultFault", Name="SecurityFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.RedirectFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardReleaseRedirectFaultFault", Name="RedirectFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SystemFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardReleaseSystemFaultFault", Name="SystemFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.BusinessFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardReleaseBusinessFaultFault", Name="BusinessFault", Namespace="http://schema.bloyal.com/3.5")]
        ConfigApp.PaymentEngine.CardResponse CardRelease(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardReleaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/CardRelease", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/CardReleaseResponse")]
        System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> CardReleaseAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardReleaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/CardCapture", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/CardCaptureResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SecurityFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardCaptureSecurityFaultFault", Name="SecurityFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.RedirectFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardCaptureRedirectFaultFault", Name="RedirectFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.SystemFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardCaptureSystemFaultFault", Name="SystemFault", Namespace="http://schema.bloyal.com/3.5")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConfigApp.PaymentEngine.BusinessFault), Action="http://service.bloyal.com/3.5/PaymentEngine/CardCaptureBusinessFaultFault", Name="BusinessFault", Namespace="http://schema.bloyal.com/3.5")]
        ConfigApp.PaymentEngine.CardResponse CardCapture(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardCaptureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://service.bloyal.com/3.5/PaymentEngine/CardCapture", ReplyAction="http://service.bloyal.com/3.5/PaymentEngine/CardCaptureResponse")]
        System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> CardCaptureAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardCaptureRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaymentEngineChannel : ConfigApp.PaymentEngine.PaymentEngine, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentEngineClient : System.ServiceModel.ClientBase<ConfigApp.PaymentEngine.PaymentEngine>, ConfigApp.PaymentEngine.PaymentEngine {
        
        public PaymentEngineClient() {
        }
        
        public PaymentEngineClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentEngineClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentEngineClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentEngineClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConfigApp.PaymentEngine.CardResponse GetCardBalance(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardBalanceRequest request) {
            return base.Channel.GetCardBalance(deviceAccessKey, storeCode, deviceCode, request);
        }
        
        public System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> GetCardBalanceAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardBalanceRequest request) {
            return base.Channel.GetCardBalanceAsync(deviceAccessKey, storeCode, deviceCode, request);
        }
        
        public ConfigApp.PaymentEngine.CardResponse CardCredit(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardCreditRequest request) {
            return base.Channel.CardCredit(deviceAccessKey, storeCode, deviceCode, request);
        }
        
        public System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> CardCreditAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardCreditRequest request) {
            return base.Channel.CardCreditAsync(deviceAccessKey, storeCode, deviceCode, request);
        }
        
        public ConfigApp.PaymentEngine.CardResponse CardRedeem(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardRedeemRequest request) {
            return base.Channel.CardRedeem(deviceAccessKey, storeCode, deviceCode, request);
        }
        
        public System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> CardRedeemAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardRedeemRequest request) {
            return base.Channel.CardRedeemAsync(deviceAccessKey, storeCode, deviceCode, request);
        }
        
        public ConfigApp.PaymentEngine.CardResponse CardDebit(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardDebitRequest request) {
            return base.Channel.CardDebit(deviceAccessKey, storeCode, deviceCode, request);
        }
        
        public System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> CardDebitAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardDebitRequest request) {
            return base.Channel.CardDebitAsync(deviceAccessKey, storeCode, deviceCode, request);
        }
        
        public ConfigApp.PaymentEngine.CardResponse CardRefund(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardRefundRequest request) {
            return base.Channel.CardRefund(deviceAccessKey, storeCode, deviceCode, request);
        }
        
        public System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> CardRefundAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardRefundRequest request) {
            return base.Channel.CardRefundAsync(deviceAccessKey, storeCode, deviceCode, request);
        }
        
        public ConfigApp.PaymentEngine.CardResponse CardAuthorize(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardAuthorizeRequest request) {
            return base.Channel.CardAuthorize(deviceAccessKey, storeCode, deviceCode, request);
        }
        
        public System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> CardAuthorizeAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardAuthorizeRequest request) {
            return base.Channel.CardAuthorizeAsync(deviceAccessKey, storeCode, deviceCode, request);
        }
        
        public ConfigApp.PaymentEngine.CardResponse CardRelease(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardReleaseRequest request) {
            return base.Channel.CardRelease(deviceAccessKey, storeCode, deviceCode, request);
        }
        
        public System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> CardReleaseAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardReleaseRequest request) {
            return base.Channel.CardReleaseAsync(deviceAccessKey, storeCode, deviceCode, request);
        }
        
        public ConfigApp.PaymentEngine.CardResponse CardCapture(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardCaptureRequest request) {
            return base.Channel.CardCapture(deviceAccessKey, storeCode, deviceCode, request);
        }
        
        public System.Threading.Tasks.Task<ConfigApp.PaymentEngine.CardResponse> CardCaptureAsync(string deviceAccessKey, string storeCode, string deviceCode, ConfigApp.PaymentEngine.CardCaptureRequest request) {
            return base.Channel.CardCaptureAsync(deviceAccessKey, storeCode, deviceCode, request);
        }
    }
}
